services:
  ollama-appECM:
    image: ollama/ollama:latest
    container_name: ollama-appECM
    restart: unless-stopped
    volumes:
      - ./ollama-appA:/root/.ollama
    networks:
      - excuse_net
    # ports:
    #   - "11434:11434"

  backend:
    build: ./backend
    container_name: excuse-backend
    restart: unless-stopped
    depends_on:
      - ollama-appECM 
    ports:
      - "3000:3000"
    environment:
      - OLLAMA_URL=http://ollama-appECM:11434
      - OLLAMA_MODEL=phi3:mini
    networks:
      - excuse_net

networks:
  excuse_net: